---
title: "Analysis of School Shootings in the US 1990 - "
author: "Zhiling Chen, Yihan Zhou, Jiatong Lyu"
output:
  html_document:
    fig_width: 8
    code_folding: hide
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=4,
                      echo=FALSE, warning=FALSE, message=FALSE)
```

# Data Set Overview

The following data set is looking at school shootings in the US from 1990 to present.This data set was retrieved from kaggle. The data includes the data, city, state, area type, school, fatalities, wounded, dupe, source and desc. Furthermore, the data set includes information regarding Census numbers on elementary school, high school and college populations through 2016.

# Goal of Analysis

The goal of the analysis is to get a better understanding of the victims / suspects that are involved in school shootings. Some questions to ask, 

# Data Prep
This dataset provided us a lot of valuable information with two csv files. 

The csv file named “cps_01_formatted”shows Census numbers on elementary school, high school and college populations through 2016. (2017 and 2018 are extrapolated.)The X Column shows  the number of population with specific types of schools (N is Nursery School, K is Kindergarten, E is Elementary School, H is High School and C is College). The Y column shows the yearly total population with one type of school.

Another file named “pah_wikp_combo” provides the dataset of the Pah/Amaral/Hagan research on school shootings from 1990. Y column indicates the date with specific month,date and year. Date means date of total incident,City means location of incident,State means  location of incident, Area Type: urban or suburban (only in Pah dataset). For data type named School, C is college, HS is high school, MS is middle school, ES is elementary school, - = unknown. The data type named Fatalities indicate the number of killed. Wounded means wounded (only in Wikipedia dataset). Dupe shows whether this incident appears in both datasets. Note means only the "Pah '' version of the incident is marked. Source shows the source either from Pah or Wikp. Desc: text description of incident (only in Wikipedia dataset)



# General Analysis of dataset on school shooting from 选个时间 to 选个时间
School shooting by city
School shooting by state
School shooting by school type
School shooting by Fatalities
School shooting by areatype


# Distribution of Data


#Central Limit Theorem 

#Sampling

#Conclusion
 
